version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASS=
      - DB_NAME=persional
    extra_hosts:
      - "host.docker.internal:host-gateway"
